on:
  push:
    branches:
      - master
name: ðŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy Test
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v2
    
    - name: ðŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: sftp.domeneshop.no
        username: ${{ secrets.stoff_username }}
        password: ${{ secrets.stoff_password }}
        protocol: ftp
        server-dir: /test/wp-content/themes/stoff/
  web-deploy:
    name: ðŸŽ‰ Deploy Main
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v2
    
    - name: ðŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: sftp.domeneshop.no
        username: ${{ secrets.stoff_username }}
        password: ${{ secrets.stoff_password }}
        protocol: ftp
        server-dir: /www/wp-content/themes/stoff/
